#!/bin/bash
set -eux
cargo install --git https://github.com/facet-rs/facet-dev
# Note: wasm32 compilation check would require disabling tokio/net feature at the workspace level
# For now, rely on facet-dev checks and CI for wasm32 validation
facet-dev pre-push

